/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package filetransfer;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ScrambleTest {
    private static long seed = 139587135L;
    private static byte[] testArray = new byte[]
    {
        13, 110, -12, 57, 0, 1, 17, 17, 9
    };

    @Test void scrambleThrowsNoException()
    {
        byte[] scrambled = Scramble.scramble(testArray, seed);
    }

    @Test void unscrambleThrowsNoException()
    {
        byte[] unscrambled = Scramble.unscramble(testArray, seed);
    }

    @Test void scrambleSizeIdentical()
    {
        byte[] scrambled = Scramble.scramble(testArray, seed);
        assertEquals(scrambled.length, testArray.length);
    }

    @Test void unscrambleSizeIdentical()
    {
        byte[] unscrambled = Scramble.unscramble(testArray, seed);
        assertEquals(unscrambled.length, testArray.length);
    }

    @Test void scrambledArrayIsScrambled()
    {
        int matchCount = 0;
        byte[] scrambled = Scramble.scramble(testArray, seed);
        for (int i = 0; i < scrambled.length; i++)
        {
            if (testArray[i] == scrambled[i])
            {
                matchCount++;
            }
        }
        assertNotEquals(matchCount, testArray.length);
    }

    @Test void preScrambleArrayMatchesUnscrambledArray() 
    {
        byte[] scrambled = Scramble.scramble(testArray, seed);
        byte[] unscrambled = Scramble.unscramble(scrambled, seed);

        assertArrayEquals(testArray, unscrambled);
    }

    @Test void hashingFunctionNonZero()
    {
        long res = Scramble.seedFromString("This string surely must have a nonzero hash!");
        assertNotEquals(res, 0);
    }
}
